--- 
abstract: ~
author: Eriam Schaffter <eriam@cpan.org>
build_requires: 
  POE::Component::Server::SimpleHTTP: 0
distribution_type: module
generated_by: Module::Install version 0.65
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Wx-Data
no_index: 
  directory: 
    - inc
    - t
requires: 
  Alien::wxWidgets: 0
  Class::Inspector: 0
  Data::Serializer: 0
  POE: 0.38
  POE::Loop::Wx: 0.03
  Wx: 0
version: 0.01_01
